apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: router-ingress-creator-role
rules:
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["create", "get", "list", "watch", "delete", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: router-ingress-creator-role-binding
subjects:
  - kind: ServiceAccount
    name: fission-router
    namespace: fission
roleRef:
  kind: Role
  name: router-ingress-creator-role
  apiGroup: rbac.authorization.k8s.io
