---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fission
spec:
  interval: 30m
  chart:
    spec:
      chart: fission-all
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: fission
      interval: 12h
  values:
    serviceType: ClusterIP
    routerServiceType: ClusterIP
    defaultNamespace: fission
    serviceMonitor:
      enabled: true
      namespace: monitoring
      additionalServiceMonitorLabels:
        release: monitoring
    podMonitor:
      enabled: true
      namespace: monitoring
      additionalPodMonitorLabels:
        release: monitoring
    grafana:
      namespace: monitoring
      dashboards:
        enable: true
