---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: fission
spec:
  interval: 24h
  url: https://fission.github.io/fission-charts/
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: fission
spec:
  interval: 5m0s
  url: https://github.com/fission/fission
  ref:
    tag: v1.20.1
