apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  name: weather
spec:
  prefix: /weather
  methods:
    - GET
  functionref:
    type: name
    name: weather
  createingress: true
  ingressconfig:
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: tibuzin-cluster-issuer
    path: /weather
    host: "api.tibuzin.127.0.0.1.sslip.io"
    tls: "api.tibuzin.127.0.0.1.sslip.io"
