apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system

resources:
  - ../base
  - infrastructure/cinder-csi.yaml
  - infrastructure/cloud-controller-manager.yaml
  - infrastructure/letsencrypt-issuer.yaml

patches:
  - target:
      group: kustomize.toolkit.fluxcd.io
      version: v1
      kind: Kustomization
      name: hello-world-function
    path: overlays/functions/hello-world.yaml
  - target:
      group: kustomize.toolkit.fluxcd.io
      version: v1
      kind: Kustomization
      name: weather-function
    path: overlays/functions/weather.yaml
  - target:
      group: kustomize.toolkit.fluxcd.io
      version: v1
      kind: Kustomization
      name: monitoring
    path: overlays/infrastructure/monitoring.yaml
