---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tibuzin-ca
spec:
  isCA: true
  commonName: tibuzin-ca
  secretName: tibuzin-ca
  issuerRef:
    name: tibuzin-selfsigned-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
