---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: tibuzin-selfsigned-cluster-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: tibuzin-cluster-issuer
spec:
  ca:
    secretName: tibuzin-ca
