---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "58.0.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      interval: 12h
