apiVersion: fission.io/v1
kind: Function
metadata:
  name: hello-world
spec:
  environment:
    name: node16
    namespace: fission
  package:
    packageref:
      name: hello-world
      namespace: fission
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
    StrategyType: execution
