apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  name: hello-world
spec:
  relativeurl: /
  methods:
    - GET
  functionref:
    type: name
    name: hello-world
  createingress: true
  ingressconfig:
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: tibuzin-cluster-issuer
    path: /
    host: "api.tibuzin.127.0.0.1.sslip.io"
    tls: "api.tibuzin.127.0.0.1.sslip.io"
