apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: tibuzin-cluster-issuer
spec:
  acme:
    email: webmaster@do-2021.fr
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: tibuzin-cluster-issuer-account-key
    solvers:
      - http01:
          ingress:
            class: nginx
