---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fission-environments
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: tibuzin
  path: infrastructure/fission-environments
  dependsOn:
    - name: fission
    - name: nginx
    - name: cert-manager
